plugins {
    // Spotless is applied by alias, NOT via the anfas.quality convention plugin: applying a
    // convention plugin here would put the convention project's whole runtime classpath
    // (including the Kotlin plugins) on the root buildscript classpath, which every subproject
    // inherits — and subprojects then fail with "already on the classpath with an unknown
    // version". Modules get formatting through their anfas.* plugin instead; this covers the
    // root-level scripts only.
    alias(libs.plugins.spotless)

    // this is necessary to avoid the plugins to be loaded multiple times
    // in each subproject's classloader
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidMultiplatformLibrary) apply false
    alias(libs.plugins.composeMultiplatform) apply false
    alias(libs.plugins.composeCompiler) apply false
    alias(libs.plugins.kotlinJvm) apply false
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.ktor) apply false
}

spotless {
    kotlinGradle {
        target("*.gradle.kts")
        ktlint(libs.versions.ktlint.get()).editorConfigOverride(
            mapOf(
                "ktlint_standard_kdoc" to "disabled",
                "max_line_length" to "100",
            ),
        )
        endWithNewline()
        trimTrailingWhitespace()
    }
}

// --- iOS version plumbing ----------------------------------------------------------------
//
// Xcode reads .xcconfig files before any build phase runs, so iOS cannot consume
// gradle/version.properties at build time the way Android and desktop do. Instead the values
// are generated into a committed Version.xcconfig, and a verify task fails the build if the
// committed file has drifted -- so a fresh clone always has a plain file Xcode can read, and
// disagreement is a build failure rather than a store-rejection surprise.
//
// The properties file is parsed inline here rather than reusing com.anfas.buildlogic.appVersion:
// the root buildscript classpath deliberately does not carry build-logic (see the note on the
// spotless alias above), and putting it there would leak the Kotlin plugins into every
// subproject.
//
// The expected text is rendered at CONFIGURATION time and only the resulting String is captured
// by the task actions. Referencing a script-level function from inside doLast fails the
// configuration cache with "cannot serialize Gradle script object references".

val versionProperties =
    providers.fileContents(layout.projectDirectory.file("gradle/version.properties")).asText.get()

val iosVersionConfig: String = run {
    val entries = versionProperties.lineSequence()
        .map(String::trim)
        .filter { it.isNotEmpty() && !it.startsWith("#") }
        .mapNotNull { line ->
            val i = line.indexOf('=')
            if (i <= 0) null else line.substring(0, i).trim() to line.substring(i + 1).trim()
        }
        .toMap()
    val name = requireNotNull(entries["versionName"]) { "versionName missing" }
    val code = requireNotNull(entries["versionCode"]) { "versionCode missing" }
    buildString {
        appendLine("// GENERATED by ./gradlew generateIosVersionConfig -- do not edit.")
        appendLine("// Source of truth: gradle/version.properties")
        appendLine("MARKETING_VERSION=$name")
        appendLine("CURRENT_PROJECT_VERSION=$code")
    }
}

val iosVersionConfigFile = layout.projectDirectory.file("app/iosApp/Configuration/Version.xcconfig")

val generateIosVersionConfig by tasks.registering {
    group = "versioning"
    description = "Writes app/iosApp/Configuration/Version.xcconfig from gradle/version.properties."
    val expected = iosVersionConfig
    val output = iosVersionConfigFile.asFile
    inputs.property("expected", expected)
    outputs.file(output)
    doLast { output.writeText(expected) }
}

val verifyIosVersionConfig by tasks.registering {
    group = "verification"
    description = "Fails if Version.xcconfig has drifted from gradle/version.properties."
    val expected = iosVersionConfig
    val committed = iosVersionConfigFile.asFile
    inputs.property("expected", expected)
    // The file is deliberately NOT declared as an input: generateIosVersionConfig produces it,
    // and declaring it here makes Gradle report an implicit task dependency. A verification task
    // that asserts on committed state should just always run.
    outputs.upToDateWhen { false }
    doLast {
        val actual = committed.takeIf { it.isFile }?.readText()
        if (actual != expected) {
            throw GradleException(
                "app/iosApp/Configuration/Version.xcconfig is out of date with " +
                    "gradle/version.properties. Run ./gradlew generateIosVersionConfig " +
                    "and commit the result.",
            )
        }
    }
}

// The base plugin (via Spotless) already contributes `check` to the root project.
tasks.named("check") { dependsOn(verifyIosVersionConfig) }
